### ISSUE TITLE
Uvoz podatkov

### ISSUE THREAD

**Issue by evgenijja** [evgenijja/Cineplexx#3]
@jaanos

Pri uvozu podatkov, ki sva jih pridobili z Mockaroojem, sva naleteli na težavo in bi potrebovali pomoč. Pri branju CSV datoteke imava nekatere podatke, ki vsebujejo vejico in nama jih csv.reader loči kljub temu, da spadajo v isti stolpec. Potem pri insertu dobiva več vrednosti kot je stolpcev in program vrne napako. Ali lahko kako prebereva CSV datoteko, da se nama to ne zgodi? Funkcija uvoziCSV namreč pri tabelah, kjer se to ne dogaja, lepo deluje in uvozi podatke v bazo. 

Vse datoteke za uvoz se nahajajo v mapi uvoz, podatki pa v mapi podatki.

Hvala in lep pozdrav!

**Comment by jaanos** [comment]
Mislim, da je problem tukaj:
https://github.com/evgenijja/Cineplexx/blob/990d2e76ac5178207150422fae90882cdc6103f4/uvoz/uvozi3.py#L131
Če je vstavljanje imena tabele in stolpcev s `format` še sprejemljivo (čeprav obstaja [boljši način](https://www.psycopg.org/docs/sql.html#module-psycopg2.sql)), pa se tega ne uporablja za vstavljanje podatkov, saj lahko pride do napadov [SQL](https://en.wikipedia.org/wiki/SQL_injection) [injection](https://xkcd.com/327/). Namesto tega za vsak podatek pišita `%s` in ga potem navedita v seznamu kot drugi parameter metode `execute`.

Vse skupaj bi šlo nekako tako:
```python
from psycopg2 import sql
...
def uvoziCSV(csv_tabela): # sprejme 'kino', 'karta' ...
    with open('podatki/{0}.csv'.format(csv_tabela), encoding="UTF-8") as csvfile:
        podatki = csv.reader(csvfile)
        # preberi prvo vrstico iz CSV
        glava = next(podatki)
        # pripravi predlogo za vstavljanje stolpcev
        stolpci = "(%s)" % ", ".join(["{}"] * len(glava))
        # pripravi predlogo za vstavljanje podatkov
        vrednosti = "(%s)" % ", ".join(["%s"] * len(glava))
        # vstavi ime tabele in stolpcev
        poizvedba = sql.SQL(" ".join(["INSERT INTO {}", stolpci, "VALUES", vrednosti])) \
            .format(sql.Identifier(csv_tabela), *(sql.Identifier(stolpec) for stolpec in glava))
        # gre čez ostale vrstice eno po eno - ne prebere celotne datoteke takoj!
        for vrstica in podatki:
            cur.execute(poizvedba, vrstica) # izvede poizvedbo
    # izvede se po uspešnem uvozu - če gre prej kaj narobe, naj se vse zavrže!
    conn.commit()
    print('uvoženo {0}'.format(csv_tabela))
```

**Comment by jaanos** [comment]
Še to: opažam, da imajo filmi lahko več žanrov. Namesto, da imata vse v enem stolpcu, bo bolje narediti tabelo žanrom in še eno vezno tabelo (relacijo), ki povezuje filme z žanri.

**Comment by evgenijja** [comment]
Hvala za pomoč vendar nama funkcije še kar ni uspelo popraviti na tak način. Uspeli sva napisati nekaj "za silo" bi pa prosili če si lahko jutri na vajah vzamete nekaj časa.
Lep pozdrav!
