### ISSUE TITLE
Binder in zaključek projekta

### ISSUE THREAD

**Issue by evgenijja** [evgenijja/Cineplexx#4]
@jaanos

Poskušava zagnati Binder vendar nama vrača napako "500 Internal Server Error." Kaj bi lahko bil problem?

Drugače sva z projektom praktično zaključili. Ali bi bilo še kaj vsebinskega za popraviti?

**Comment by jaanos** [comment]
Samo na hitro glede Binderja: manjka vama `auth_public.py`, kjer naj bodo podatki za prijavo z uporabnikom `javnost` (ta naj ima seveda ustrezne pravice na bazi). Seveda brez tega programa tudi sam ne morem pognati.

**Comment by evgenijja** [comment]
Sem dodala ustrezno datoteko.

**Comment by jaanos** [comment]
Glede na to, da projekt v splošnem deluje, bom dodal povezavo na repozitorij predmeta, tako da se lahko z @alenFMF domenita za termin zagovora, če se seveda še nista. Če bosta do takrat še kaj spreminjali, mi javita, da posodobim povezavo.

Imam pa še nekaj pripomb:

* V tabelah `ima_zanr`, `na_voljo` in `vrti` manjka glavni ključ - ta naj v vseh primerih sestoji iz obeh referenc.

* Pri kinih, prigrizkih in žanrih naj bo glavni ključ (namesto nizov) ID tipa `SERIAL` (seveda bo potrebno ustrezno popraviti reference na te tabele, ki naj bodo potem tipa `INTEGER`).

* Zakaj v podatkih ni presledkov? Kolikor vidim, to naredita pri uvozu:
https://github.com/evgenijja/Cineplexx/blob/ae563d025fc4cae06736e408f9570bb6afcb4112/uvoz/uvozi_podatke.py#L170-L171

* Pazita na velikost črk v končnicah slik - nekatere imajo končnico `.png`, druge pa `.PNG`, kar naj ustreza navedenim imenom v predlogah. Tako se bodo slike ustrezno prikazale na Binderju (in na splošno na sistemih, kjer je velikost črk v imenih datotek pomembna).

* Tudi pri `redirect` poskrbita, da se pot začne z `ROOT`. Tako lahko tukaj
https://github.com/evgenijja/Cineplexx/blob/ae563d025fc4cae06736e408f9570bb6afcb4112/priklop2.py#L47
naredita enostavno `redirect(ROOT)`.

* Svetujem, da v predlogah uporabita `rebase` (kolikor vidim, ga imata zakomentiranega), da ne bo potrebno ponavljati ogrodja v vsaki predlogi.

* Pri seznamu žanrov izpisujeta kar celotne vrstice kot sezname:
https://github.com/evgenijja/Cineplexx/blob/ae563d025fc4cae06736e408f9570bb6afcb4112/views/zanr.html#L79-L83
Če želita izluščiti edino vrednost iz vrstice, lahko naredita `%for (ime, ) in zanr:`. Svetoval bi še, da omogočita uporabniku, da klikne na žanr in dobi seznam vseh filmov tega žanra.

* Pri sporedu in seznamu filmov po žanru bi lahko izpisali vsaj ime filma (uporabita ustrezen `JOIN`). Spored bi bilo smiselno urediti po času, dovoliti bi bilo smiselno tudi filtriranje po kinu.

* Vajina prijava ne uporablja piškotkov, pač pa samo prikaže stran, do katere sicer ni povezave (in ima povezave do še več takih strani). Poskrbita, da se ob prijavi ustrezno nastavijo piškotki, tako da onemogočita dostop do internih strani brez prijave. Svetujem tudi, da imata podatke za prijavo v bazi (tudi, če bosta imeli samo enega uporabnika). Najbolje bo, da pogledata k drugim projektom, kako imajo to urejeno.

* Prijavljeni uporabnik nima nobene možnosti urejanja baze. Pri kartah je sicer možno preurejati seznam in odstranjevati karte, a to vpliva le na trenutni prikaz. Svetujem, da preurejanje odstranita, odstranjevanje pa naj pobriše karto iz baze; omogočita tudi dodajanje. Podobno lahko naredita tudi pri dvoranah in filmih, ter omogočita še urejanje sporeda.

Mimogrede, ko naredita zahtevek `POST` in se stanje na strežniku spremeni (bodisi odjava/prijava - sprememba v piškotkih, ali pa sprememba v bazi), se spodobi, da naredita preusmeritev (tako ponovno nalaganje strani ne bo ponovilo dejanja). Prikaz strani brez preusmeritve je smiseln le v primeru napake, pri kateri ne pride do spremembe stanja (in se lahko uporabniku spet ponudijo vneseni podatki).

**Comment by evgenijja** [comment]
Nekaj sva uspeli popraviti, tako da bi bilo treba posodobiti povezavo.

**Comment by jaanos** [comment]
V redu, sem posodobil.
